#!/bin/sh

set -e

detect_platform () {
  OS=$(uname -s)
  ARCH=$(uname -m)
  echo "${OS}_${ARCH}"
}

ensure_command () {
  if command -v "$1" 1>/dev/null 2>&1; then
    return 0
  else
    echo "$1 is not installed. Please install it to proceed." 1>&2
    exit 1
  fi
}

ensure_command "curl"
ensure_command "uname"

PLATFORM=$(detect_platform)

VERSION=v1.30.0
curl -LO "https://github.com/llmariner/llmariner/releases/download/${VERSION}/llmariner_${PLATFORM}.tar.gz"
tar -xvf llmariner_${PLATFORM}.tar.gz llma
chmod u+x ./llma
rm llmariner_${PLATFORM}.tar.gz
