#!/bin/sh

set -e

detect_os () {
  RAW_OS=$(uname -s)
  OS="linux"
  case "$RAW_OS" in
    "Linux") OS="linux";;
    "Darwin") OS="darwin";;
    *) echo "Unsupported operating system \"${RAW_OS}\"" 1>&2; exit 1;;
  esac
  echo "${OS}"
}

detect_architecture () {
  RAW_ARCH=$(uname -m)
  ARCH="x86_64"
  case "$RAW_ARCH" in
    "x86_64") ARCH="x86_64";;
    "arm64") ARCH="arm64";;
    *) echo "Unsupported architecture \"${RAW_ARCH}\"" 1>&2; exit 1;;
  esac
  echo "${ARCH}"
}

detect_platform () {
  OS=$(detect_os)
  ARCH=$(detect_architecture)
  echo "${OS}-${ARCH}"
}

ensure_command () {
  if command -v "$1" 1>/dev/null 2>&1; then
    return 0
  else
    echo "$1 is not installed. Please install it to proceed." 1>&2
    exit 1
  fi
}

ensure_command "curl"
ensure_command "uname"

PLATFORM=$(detect_platform)

curl -LO http://llmariner-artifacts.s3.amazonaws.com/artifacts/cli/0.132.0/"${PLATFORM}"/llma
